# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Build and Basic test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    tags:
      - "*"      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: IBM-Blockchain/ansible-collection
          path: ansiblecollection

      - name: Build Docker image
        run: |
          docker build -t ofs-ansible ansiblecollection

      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true
          version: "v0.14.0"
      - uses: extractions/setup-just@v1
      - name: production test flow
        run: |
          just kind review-config operator console
