name: Asset Tx Contract Image CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'contracts/asset-tx-typescript/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'contracts/asset-tx-typescript/**'

jobs:
  docker_build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yaml
    with:
      imagename: full-stack-asset-transfer-guide/contracts/asset-tx-typescript
      path: contracts/asset-tx-typescript
      chaincode: true